### ISSUE TITLE
Export of nodes with spaces in the name fails

### ISSUE THREAD

**Issue by aro** [GlennRicaud/data-toolbox-app#47]
Trying to export nodes that contains a white space in the node name does not include all the selected nodes. The export zip is generated without errors but there are missing nodes.

The issue was found in a Docker instance, but it could not be reproduced locally on Mac.

Stack trace:
```Java
06:47:23.733 ERROR c.e.x.p.i.e.ExceptionRendererImpl - com.enonic.xp.resource.ResourceProblemException: Error while zipping files
com.enonic.xp.web.WebException: com.enonic.xp.resource.ResourceProblemException: Error while zipping files
	at com.enonic.xp.web.impl.dos.DosFilterWrapper.doFilter(DosFilterWrapper.java:64)
	at com.enonic.xp.web.impl.dispatch.mapping.FilterDefinitionImpl.doFilter(FilterDefinitionImpl.java:40)
	at com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:50)
	at com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:36)
	at com.enonic.xp.web.impl.dispatch.pipeline.FilterPipelineImpl.filter(FilterPipelineImpl.java:29)
	at com.enonic.xp.web.impl.dispatch.DispatchServletImpl.service(DispatchServletImpl.java:35)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:821)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:375)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1158)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:240)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:306)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: com.enonic.xp.resource.ResourceProblemException: Error while zipping files
	at com.enonic.xp.trace.Tracer.trace(Tracer.java:56)
	at com.enonic.xp.trace.Tracer.trace(Tracer.java:95)
	at com.enonic.xp.portal.impl.controller.ControllerScriptImpl.execute(ControllerScriptImpl.java:34)
	at com.enonic.xp.portal.impl.handler.service.ServiceHandlerWorker.execute(ServiceHandlerWorker.java:75)
	at com.enonic.xp.portal.impl.handler.service.ServiceHandler.doHandle(ServiceHandler.java:63)
	at com.enonic.xp.portal.impl.handler.service.ServiceHandler.doHandle(ServiceHandler.java:22)
	at com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:71)
	at com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:30)
	at com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:75)
	at com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:30)
	at com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:75)
	at com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:30)
	at com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:75)
	at com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:30)
	at com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:75)
	at com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:30)
	at com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:75)
	at com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:30)
	at com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:75)
	at com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:30)
	at com.enonic.xp.web.impl.handler.WebDispatcherImpl.dispatch(WebDispatcherImpl.java:50)
	at com.enonic.xp.web.impl.handler.WebDispatcherServlet.doHandle(WebDispatcherServlet.java:135)
	... 87 common frames omitted
Caused by: com.enonic.xp.resource.ResourceProblemException: Error while zipping files
	at com.enonic.xp.resource.ResourceProblemException$Builder.build(ResourceProblemException.java:131)
	at com.enonic.xp.script.impl.util.ErrorHelper.doHandleException(ErrorHelper.java:54)
	at com.enonic.xp.script.impl.util.ErrorHelper.handleError(ErrorHelper.java:27)
	at com.enonic.xp.script.impl.value.FunctionScriptValue.call(FunctionScriptValue.java:41)
	at com.enonic.xp.script.impl.executor.ScriptExportsImpl.executeMethod(ScriptExportsImpl.java:56)
	at com.enonic.xp.portal.impl.controller.ControllerScriptImpl.doExecute(ControllerScriptImpl.java:62)
	at com.enonic.xp.portal.impl.controller.ControllerScriptImpl.lambda$execute$0(ControllerScriptImpl.java:34)
	at com.enonic.xp.trace.Tracer.traceEx(Tracer.java:69)
	at com.enonic.xp.trace.Tracer.trace(Tracer.java:52)
	... 116 common frames omitted
Caused by: systems.rcd.fwk.core.exc.RcdException: Error while zipping files
	at systems.rcd.fwk.core.util.zip.impl.RcdSimpleZipService.instZip(RcdSimpleZipService.java:67)
	at systems.rcd.fwk.core.util.zip.RcdZipService.zip(RcdZipService.java:15)
	at systems.rcd.enonic.datatoolbox.RcdExportScriptBean.download(RcdExportScriptBean.java:192)
	at jdk.nashorn.internal.scripts.Script$Recompilation$294$130A$export_download.L:1#post(systems.rcd.enonic.datatoolbox:/services/export-download/export-download.js:9)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:639)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.ScriptObjectMirror.call(ScriptObjectMirror.java:117)
	at com.enonic.xp.script.impl.value.FunctionScriptValue.call(FunctionScriptValue.java:36)
	... 121 common frames omitted
Caused by: java.nio.file.NoSuchFileException: /enonic-xp/home/data/export/enonic-homepage-2017-10-06T08-46-33/enonic-homepage/case-studies/screen-grabs/get.no desktop.png
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at java.nio.file.Files.readAttributes(Files.java:1737)
	at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219)
	at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
	at java.nio.file.FileTreeWalker.next(FileTreeWalker.java:372)
	at java.nio.file.Files.walkFileTree(Files.java:2706)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at systems.rcd.fwk.core.util.zip.impl.RcdSimpleZipService.instZip(RcdSimpleZipService.java:39)
	... 129 common frames omitted
```

**Comment by GlennRicaud** [comment]
Some more info on the OS that the docker instance is using?
Was it hosted by us or by the client?

**Comment by GlennRicaud** [comment]
Closing issue. Was not linked to DT in the end
